server:
  port: 8888
eureka:
  instance:
#    hostname: localhost #Eureka服务端的实例名称
    hostname: eureka8888.com #Eureka服务端的实例名称
  client:
    registerWithEureka: false #false表示不向注册中心注册自己
    fetchRegistry: false #false表示本端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置与Eureka Server交互的地址,查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7777.com:7777/eureka/,http://eureka9999.com:9999/eureka/
