eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7777.com:7777/eureka/,http://eureka8888.com:8888/eureka/,http://eureka9999.com:9999/eureka/
  instance:
      instance-id: gateway-7001.com #自定义Eureka微服务管理页面的显示别名
      prefer-ip-address: true #访问路径可以显示IP地址，默认为false 不显示

server:
  port: 7001

spring:
  application:
    name: service-zuul-gateway

zuul:
  routes:
    service-provider:
      path: /myservice/** #服务名映射的url
      serviceId: service-member #服务提供方的id
  ignored-services: "*" #忽略的服务名，配置后无法通过服务id访问，"*"表示多个
  prefix: /cloud #访问url前缀，在服务名映射的url之前

info:
  app.name: charver-springclouddemo-servicemember
  company.name: www.chavaer.com
  contact.name: chavaer
  contact.phone: 188-3288-3388
  contace.email: chavaer@super.com.cn

